#!/bin/bash -e

SUPERVISORD=/usr/local/bin/supervisord
PIDFILE=/rinjani/var/supervisord.pid
OPTS="-c /rinjani/app/conf/supervisord.conf"
DAEMONUSER=ron

test -x $SUPERVISORD || exit 0

. /lib/lsb/init-functions

export PATH="${PATH:+$PATH:}/usr/local/bin:/usr/sbin:/sbin"

case "$1" in
  start)
        log_begin_msg "Starting Supervisor daemon manager..."
        start-stop-daemon --start -q -p $PIDFILE -c $DAEMONUSER -x $SUPERVISORD -- $OPTS || log_end_msg 1
        log_end_msg 0
        ;;
  stop)
        log_begin_msg "Stopping Supervisor daemon manager..."
        start-stop-daemon --stop -v --oknodo -u $DAEMONUSER -p $PIDFILE || log_end_msg 1
        log_end_msg 0
        ;;

  restart|reload|force-reload)
        log_begin_msg "Restarting Supervisor daemon manager..."
        start-stop-daemon --stop -v --oknodo -u $DAEMONUSER -p $PIDFILE --retry 30
        start-stop-daemon --start -q -p $PIDFILE -c $DAEMONUSER -x $SUPERVISORD -- $OPTS || log_end_msg 1
        ;;

  *)
        log_success_msg "Usage: /etc/init.d/supervisor {start|stop|reload|force-reload|restart}"
        exit 1
esac

exit 0
